<a href="https://colab.research.google.com/github/Dmitri9149/TensorFlow-PyTorch-basics/blob/master/PyTorch_Padding_Stride_MultiChannels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# -U: Upgrade all packages to the newest available version
!pip install -U d2l

from d2l import torch as d2l
import torch as torch
from torch import nn
import numpy as np

     |████████████████████████████████| 61kB 4.5MB/s 


Exercises and some code modification/experimentation for the d2l.ai book : http://d2l.ai/ 

Padding

In [2]:
### initialize convolutional layer , make some changes in sizes of the layer 
### with the help of padding
def comp_conv2d(conv2d, X):
  ### (1,1) correspond to batch size and num of channels
  X = X.reshape((1,1) +  X.shape)
### elim dimentions we do not need

  Y = conv2d(X)
  return Y.reshape(Y.shape[2:])

conv2d = nn.Conv2d(1,1,kernel_size = 3, padding = 1)
X = torch.rand(size = (8,8))
comp_conv2d(conv2d,X).shape


torch.Size([8, 8])

In [3]:
conc2d = nn.Conv2d(1,1, kernel_size = (5,3), padding = [2,1])
comp_conv2d(conv2d,X).shape

torch.Size([8, 8])

Stride

In [4]:
conv2d = nn.Conv2d(1,1, kernel_size = 3, padding = 1, stride = 2)
comp_conv2d(conv2d,X).shape

torch.Size([4, 4])

In [5]:
conv2d = nn.Conv2d(1, 1, kernel_size=(3, 5), padding=(0, 1), stride=(3, 4))
comp_conv2d(conv2d, X).shape

torch.Size([2, 2])

In [6]:
### input X and kernel K , compute cross correlation
def corr2d(X,K):
  reduce_sum = lambda x, *args, **kwargs: x.sum(*args, **kwargs)
  h,w = K.shape
  Y=torch.zeros(X.shape[0] -h + 1, X.shape[1] - w + 1)
  for i in range(Y.shape[0]):
    for j in range(Y.shape[1]):
      Y[i,j]=reduce_sum((X[i:i+ h,j:j+w])*K)
  return Y

MultiChannels

In [7]:
### work with multi channels
def corr2d_multi_in(X,K):
  ## iterate via the first dimention (channels); sum results together
  ## zip 'list' of 2D inputs and kernels 
  corr = (corr2d(x,k) for x, k in zip(X,K))
  return sum(corr)

In [8]:
X = torch.tensor([[[0.0, 3.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [1.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

corr2d_multi_in(X, K)

tensor([[ 55.,  68.],
        [ 98., 113.]])

In [9]:
### multiple output and input
### size of input is (i, h, w) size of kernel is (o,i,h_k,w_k) 
def corr2d_multi_in_out(X,K):
## iterate via o -> first dim of kernel and at every step make cross correlation 
### with input X
############# iterate over first dim of K 
  return torch.stack([corr2d_multi_in(X,k) for k in K ], dim = 0)

In [10]:
K = torch.stack((K,K+1,K+2,K+3))
K.shape

torch.Size([4, 2, 2, 2])

In [11]:
corr2d_multi_in_out(X,K)

tensor([[[ 55.,  68.],
         [ 98., 113.]],

        [[ 77.,  98.],
         [142., 165.]],

        [[ 99., 128.],
         [186., 217.]],

        [[121., 158.],
         [230., 269.]]])

1 x 1 Convolutional Layers

In [12]:
def corr2d_multi_in_out_1x1(X,K):
  i,h,w = X.shape
  o = K.shape[0]
  X = X.reshape((i,h*w))
  K = K.reshape((o,i))
##  mutmul in fully connected layer
  Y = torch.matmul(K,X)
  return Y.reshape((o,h,w))


In [13]:
## 2 input channels
X = torch.normal(0, 1, (2, 3, 3)) 
### kernel will make deal with 2 inp. channels and will generate 4 outp. channels
K = torch.normal(0, 1, (4 , 2, 1, 1))
Y1 = corr2d_multi_in_out_1x1(X,K)
Y2 = corr2d_multi_in_out(X, K)

In [14]:
reduce_sum = lambda x, *args, **kwargs: x.sum(*args, **kwargs)
assert float(reduce_sum(torch.abs(Y1-Y2))) <1e-6
### no assertion error

In [15]:
Y1

tensor([[[ 0.0422, -1.9043,  2.3291],
         [-1.3286, -1.0322,  0.8546],
         [-0.7832, -0.3728,  0.3067]],

        [[ 0.7413, -0.8710,  1.6982],
         [-0.2757, -0.8245,  0.7909],
         [-0.9123,  0.3097,  0.4818]],

        [[-2.4431, -2.7201,  1.1324],
         [-3.0488, -0.2525, -0.1663],
         [ 0.8025, -2.1975, -0.7462]],

        [[ 1.6137,  3.9355, -3.3223],
         [ 3.5278,  1.3030, -0.8237],
         [ 0.3132,  1.9018,  0.1709]]])