<a href="https://colab.research.google.com/github/Dmitri9149/TensorFlow-PyTorch-basics/blob/master/PyTorch_Blocks_and_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

Some part of the code is based on d2l.ai book: http://d2l.ai/

In [2]:
### basing on the d2l.ai book 

In [3]:
net = nn.Sequential(nn.Linear(20,256), nn.ReLU(), nn.Linear(256,10))

X=torch.rand(2,20)
net(X)

tensor([[-0.1382, -0.0392,  0.1239,  0.3000,  0.0135, -0.1068, -0.2886, -0.1604,
          0.0947,  0.0331],
        [-0.0060,  0.0215,  0.2270,  0.2382,  0.1244, -0.0199, -0.1310,  0.0017,
          0.1153,  0.0025]], grad_fn=<AddmmBackward>)

In [4]:
net.forward(X)

tensor([[-0.1382, -0.0392,  0.1239,  0.3000,  0.0135, -0.1068, -0.2886, -0.1604,
          0.0947,  0.0331],
        [-0.0060,  0.0215,  0.2270,  0.2382,  0.1244, -0.0199, -0.1310,  0.0017,
          0.1153,  0.0025]], grad_fn=<AddmmBackward>)

In [5]:
class MLP(nn.Module):

    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)  # Hidden layer
        self.out = nn.Linear(256, 10)  # Output layer

    def forward(self, X):
        return self.out(F.relu(self.hidden(X)))


In [6]:
net = MLP()
net(X)

tensor([[ 0.0030, -0.3252, -0.1235,  0.3344, -0.0870,  0.3490,  0.0889, -0.1135,
          0.1467,  0.2245],
        [ 0.0127, -0.3919,  0.0524,  0.2701, -0.1078,  0.2389,  0.2186,  0.0079,
          0.1923,  0.0917]], grad_fn=<AddmmBackward>)

In [7]:
### Custom Sequential Block

In [8]:
class MySequential(nn.Module):
    def __init__(self, *args):
        super().__init__()
        for block in args:
            # Here, `block` is an instance of a `Module` subclass. We save it
            # in the member variable `_modules` of the `Module` class, and its
            # type is OrderedDict
            self._modules[block] = block

    def forward(self, X):
        # OrderedDict guarantees that members will be traversed in the order
        # they were added
        for block in self._modules.values():
            X = block(X)
        return X



In [9]:
net = MySequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10))
net(X)

tensor([[ 0.1352,  0.0498, -0.1028, -0.2970, -0.0374, -0.1706,  0.0069, -0.0619,
         -0.1751, -0.0243],
        [ 0.1370,  0.0931, -0.0839, -0.2898, -0.0013, -0.2590,  0.0712,  0.0934,
         -0.2281, -0.0223]], grad_fn=<AddmmBackward>)