<a href="https://colab.research.google.com/github/Dmitri9149/TensorFlow-PyTorch-basics/blob/master/TensorFlow_Tensors_Models_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [ ]:
### basing on https://www.tensorflow.org/tutorials

In [ ]:
print(tf.add([1, 2], [3, 4]))
print(tf.reduce_logsumexp([1.,2.,3.,4.,5.]))

tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(5.4519143, shape=(), dtype=float32)


In [ ]:
x = tf.matmul([[2]], [[3,4]])
print(x.shape)
print(x.dtype)

(1, 2)
<dtype: 'int32'>


In [ ]:
x = tf.convert_to_tensor([1,2,3,4,5])
print(x.shape)
print(x.dtype)
print(x)
x.shape

(5,)
<dtype: 'int32'>
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


TensorShape([5])

In [ ]:
x = tf.convert_to_tensor([[1,2,3,4,5]])
print(x.shape)
print(x.dtype)
print(x)
x.shape

(1, 5)
<dtype: 'int32'>
tf.Tensor([[1 2 3 4 5]], shape=(1, 5), dtype=int32)


TensorShape([1, 5])

In [ ]:
import numpy as np

In [ ]:
array = np.ones([4,6])

In [ ]:
print(tf.multiply(array,10))

tf.Tensor(
[[10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]], shape=(4, 6), dtype=float64)


In [ ]:
tensor = tf.add(np.ones([2,3]), 5)
print(tensor.numpy())

[[6. 6. 6.]
 [6. 6. 6.]]


In [ ]:
tf.random.uniform([3,4])
print(tf.config.experimental.list_physical_devices())
print(x.device.endswith('GPU:0'))

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU')]
False


In [ ]:
import time

def time_mult(x):
  start = time.time()
  for loop in range(100):
    x=tf.matmul(x,x)

  result = time.time() - start
  print('1000 loops with time {:10.2}'.format(result*1000))

# execute on CPU
print('On CPU')
with tf.device('CPU'):
  x=tf.random.uniform([1000,1000])
  assert x.device.endswith('CPU:0')
  time_mult(x)


# execute on GPU
if tf.config.experimental.list_physical_devices('GPU'):
  print('On GPU')
  with tf.device('CPU'):
    x=tf.random.uniform([1000,1000])
    assert x.device.endswith('GPU:0')
    time_mult(x)







On CPU
1000 loops with time    3.3e+03


In [ ]:
#### Datasets
ds_tensors = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])

## Create a CSV file

import tempfile

_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write(""" Line1
  Line2
  Line3
  Line4
  Line5
  Line6
  Line7
  """)

ds_file = tf.data.TextLineDataset(filename)



In [ ]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.batch(3)

In [ ]:
for x in ds_tensors:
  print(x)

tf.Tensor([4 1], shape=(2,), dtype=int32)
tf.Tensor([ 9 25], shape=(2,), dtype=int32)
tf.Tensor([36 16], shape=(2,), dtype=int32)


In [ ]:
for x in ds_file:
  print(x)

tf.Tensor([b' Line1' b'  Line2' b'  Line3'], shape=(3,), dtype=string)
tf.Tensor([b'  Line4' b'  Line5' b'  Line6'], shape=(3,), dtype=string)
tf.Tensor([b'  Line7' b'  '], shape=(2,), dtype=string)


In [ ]:
######## Layers

In [ ]:
layer = tf.keras.layers.Dense(10, input_shape =(None, 5))

In [ ]:
### in the result 7 is batch size abd 10 is the output dimention 
layer(tf.zeros([7,5]))

<tf.Tensor: shape=(7, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
layer.variables

[<tf.Variable 'dense_2/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.2738239 , -0.20546424, -0.60897404, -0.3014058 , -0.0491333 ,
          0.5836747 ,  0.19301206,  0.20641315, -0.3399754 ,  0.12718248],
        [ 0.40244645,  0.11178511,  0.3685543 ,  0.0652442 ,  0.37434798,
         -0.07283461,  0.2242375 , -0.2978989 , -0.48586088,  0.13517088],
        [-0.17718917,  0.3749066 , -0.09735745,  0.34146547,  0.2566344 ,
          0.50554806, -0.46402782,  0.05010617,  0.51790565,  0.46498066],
        [-0.47309732,  0.40424985,  0.33884114,  0.28004694,  0.50177723,
         -0.46575403,  0.32815802, -0.32384336, -0.58772904,  0.20688558],
        [-0.4555123 , -0.4154502 , -0.10926872, -0.40989977,  0.50052315,
         -0.4582755 ,  0.38584608, -0.48580718, -0.12694865,  0.12728053]],
       dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [ ]:
layer.kernel

<tf.Variable 'dense_2/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.2738239 , -0.20546424, -0.60897404, -0.3014058 , -0.0491333 ,
         0.5836747 ,  0.19301206,  0.20641315, -0.3399754 ,  0.12718248],
       [ 0.40244645,  0.11178511,  0.3685543 ,  0.0652442 ,  0.37434798,
        -0.07283461,  0.2242375 , -0.2978989 , -0.48586088,  0.13517088],
       [-0.17718917,  0.3749066 , -0.09735745,  0.34146547,  0.2566344 ,
         0.50554806, -0.46402782,  0.05010617,  0.51790565,  0.46498066],
       [-0.47309732,  0.40424985,  0.33884114,  0.28004694,  0.50177723,
        -0.46575403,  0.32815802, -0.32384336, -0.58772904,  0.20688558],
       [-0.4555123 , -0.4154502 , -0.10926872, -0.40989977,  0.50052315,
        -0.4582755 ,  0.38584608, -0.48580718, -0.12694865,  0.12728053]],
      dtype=float32)>

In [ ]:
layer.bias

<tf.Variable 'dense_2/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
#### Custom Layer

In [ ]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs

  def build(self, input_shape):
    self.kernel = self.add_weight("kernel",
                                  shape=[int(input_shape[-1]),
                                         self.num_outputs])

  def call(self, input):
    return tf.matmul(input, self.kernel)

layer = MyDenseLayer(10)

In [ ]:
layer = MyDenseLayer(10)

In [ ]:
layer.trainable_variables

[]

In [ ]:
xx = layer(tf.zeros([10, 5])) # Calling the layer `.builds` it.

In [ ]:
layer.trainable_variables

[<tf.Variable 'my_dense_layer_7/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.11522007, -0.1855245 , -0.353973  , -0.07279921, -0.15556827,
          0.4458229 , -0.17800191, -0.1662826 ,  0.00814772,  0.52057165],
        [-0.17124173, -0.59773254, -0.02089834,  0.54924303,  0.25403464,
         -0.5671085 ,  0.3639536 , -0.25701693, -0.07156575, -0.13934276],
        [ 0.6304669 ,  0.19899571, -0.5380819 , -0.38546968,  0.16092879,
          0.20993274, -0.0415085 , -0.27472907, -0.49744117,  0.23949617],
        [-0.3512187 ,  0.42951006, -0.00515443, -0.5235942 , -0.3807916 ,
         -0.43796858,  0.04748201, -0.32922474,  0.50242025,  0.2028811 ],
        [-0.17407143,  0.00988936,  0.28068238,  0.49765366, -0.19382104,
          0.50951713, -0.16435549, -0.4622969 ,  0.35464007, -0.323334  ]],
       dtype=float32)>]

In [ ]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer_7/kernel:0']


In [ ]:
print(var.name for var in layer.trainable_variables)

<generator object <genexpr> at 0x7febe31fc258>


In [ ]:
layer.kernel

<tf.Variable 'my_dense_layer_7/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.11522007, -0.1855245 , -0.353973  , -0.07279921, -0.15556827,
         0.4458229 , -0.17800191, -0.1662826 ,  0.00814772,  0.52057165],
       [-0.17124173, -0.59773254, -0.02089834,  0.54924303,  0.25403464,
        -0.5671085 ,  0.3639536 , -0.25701693, -0.07156575, -0.13934276],
       [ 0.6304669 ,  0.19899571, -0.5380819 , -0.38546968,  0.16092879,
         0.20993274, -0.0415085 , -0.27472907, -0.49744117,  0.23949617],
       [-0.3512187 ,  0.42951006, -0.00515443, -0.5235942 , -0.3807916 ,
        -0.43796858,  0.04748201, -0.32922474,  0.50242025,  0.2028811 ],
       [-0.17407143,  0.00988936,  0.28068238,  0.49765366, -0.19382104,
         0.50951713, -0.16435549, -0.4622969 ,  0.35464007, -0.323334  ]],
      dtype=float32)>

In [ ]:
#### Models

In [ ]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name='')
    filters1, filters2, filters3 = filters

    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()

  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2c(x)
    x = self.bn2c(x, training=training)

    x += input_tensor
    return tf.nn.relu(x)


block = ResnetIdentityBlock(1, [1, 2, 3])

In [ ]:
_ = block(tf.zeros([1, 2, 3, 3]))

In [ ]:
block.layers

In [ ]:
block.summary()

Model: "resnet_identity_block_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization_6 (Batch multiple                  4         
_________________________________________________________________
conv2d_7 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization_7 (Batch multiple                  8         
_________________________________________________________________
conv2d_8 (Conv2D)            multiple                  9         
_________________________________________________________________
batch_normalization_8 (Batch multiple                  12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
______________________________________________

In [ ]:
##### using Sequantial
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1),
                                                    input_shape=(
                                                        None, None, 3)),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(2, 1,
                                                    padding='same'),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(3, (1, 1)),
                             tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [ ]:
my_seq.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_9 (Conv2D)            (None, None, None, 1)     4         
_________________________________________________________________
batch_normalization_9 (Batch (None, None, None, 1)     4         
_________________________________________________________________
conv2d_10 (Conv2D)           (None, None, None, 2)     4         
_________________________________________________________________
batch_normalization_10 (Batc (None, None, None, 2)     8         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, None, None, 3)     9         
_________________________________________________________________
batch_normalization_11 (Batc (None, None, None, 3)     12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
_________________________________________________________