<a href="https://colab.research.google.com/github/Dmitri9149/TensorFlow-PyTorch-basics/blob/master/TensorFlow_Dataset_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### The bsics of working with Datasets in Tensorflow
The work is based on the official: https://www.tensorflow.org/api_docs/python/tf/data/Dataset

In [ ]:
import tensorflow as tf

In [ ]:
### tf.data.Dataset all is starting from data
### this is also the most diverse part of the work
### this part needs specail attention
## tf.data.Dataset(
##     variant_tensor
## )

In [ ]:
dataset_str = tf.data.Dataset.from_tensor_slices(["one", "two", "three"])
for element in dataset_str:
  print(element)

tf.Tensor(b'one', shape=(), dtype=string)
tf.Tensor(b'two', shape=(), dtype=string)
tf.Tensor(b'three', shape=(), dtype=string)


In [ ]:
dataset = tf.data.Dataset.from_tensor_slices([1,2,3])
for element in dataset:
  print(element)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
### as_numpy_iterator : return iterator which convert all elts to numpy
dataset = tf.data.Dataset.from_tensor_slices([1,2,3])
for element in dataset.as_numpy_iterator():
  print(element)

1
2
3


In [ ]:
dataset = dataset.map(lambda x: x**2)
list(dataset.as_numpy_iterator())

[1, 4, 9]

In [ ]:
dataset = tf.data.Dataset.range(100)
print(dataset.element_spec)
def dataset_fn(ds):
  return ds.filter(lambda x: x < 10)
dataset = dataset.apply(dataset_fn)
list(dataset.as_numpy_iterator())

TensorSpec(shape=(), dtype=tf.int64, name=None)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
import collections
from collections import namedtuple
### Element : the output from next() method on dataset iterator; 
### component -> the leaf in  the nested structure of element
a = 1 # Integer element
b = 2.0 # Float element
c = (1, 2) # Tuple element with 2 components
d = {"a": (2, 2), "b": 3} # Dict element with 3 components
Point = collections.namedtuple("Point", ["x", "y"]) # doctest: +SKIP
e = Point(1, 2) # Named tuple # doctest: +SKIP
f = tf.data.Dataset.range(10) # Dataset element

In [ ]:
dataset = tf.data.Dataset.range(9)
dataset = dataset.batch(3)
list(dataset.as_numpy_iterator())

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [ ]:
dataset = tf.data.Dataset.range(11)
dataset = dataset.batch(3)
list(dataset.as_numpy_iterator())

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10])]

In [ ]:
dataset = tf.data.Dataset.range(9)
dataset = dataset.batch(3)
dataset.cache()
### dataset = dataset.cache("/path/to/file") can cache to file 
list(dataset.as_numpy_iterator())
####  read from cache()
list(dataset.as_numpy_iterator())


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [ ]:
dataset.cardinality()

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [ ]:
a=tf.data.Dataset.range(4,9)
a.element_spec
for element in a:
  print(element)


tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)


In [ ]:
a.element_spec

TensorSpec(shape=(), dtype=tf.int64, name=None)

In [ ]:
a=tf.data.Dataset.range(4,9)
b=tf.data.Dataset.range(3,11)
c=a.concatenate(b)
c.element_spec


TensorSpec(shape=(), dtype=tf.int64, name=None)

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices([(3,4),(1,2),(5,4)])
dataset=dataset.enumerate()
for element in dataset.as_numpy_iterator():
  print(element)


(0, array([3, 4], dtype=int32))
(1, array([1, 2], dtype=int32))
(2, array([5, 4], dtype=int32))


In [ ]:
# The nested structure of the input dataset determines the structure of
# elements in the resulting dataset.
dataset = tf.data.Dataset.from_tensor_slices([(7, 8), (9, 10)])
dataset = dataset.enumerate()
for element in dataset.as_numpy_iterator():
  print(element)

(0, array([7, 8], dtype=int32))
(1, array([ 9, 10], dtype=int32))


In [ ]:
### filter()
dataset = tf.data.Dataset.from_tensor_slices([1,1,1,2,3,4,5])
def filter_fn(x):
  return tf.math.equal(x,1)

dataset=dataset.filter(filter_fn)
list(dataset.as_numpy_iterator())


[1, 1, 1]

In [ ]:
dataset= tf.data.Dataset.from_tensor_slices([[1,2,3],[3,4,5],[5,6,7]])
list(dataset)

[<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 7], dtype=int32)>]

In [ ]:
dataset.element_spec

TensorSpec(shape=(3,), dtype=tf.int32, name=None)

In [ ]:
dataset=dataset.flat_map(lambda x: tf.data.Dataset.from_tensor_slices(x))
list(dataset.as_numpy_iterator())

[1, 2, 3, 3, 4, 5, 5, 6, 7]

In [ ]:
# Slicing a tuple of 1D tensors produces tuple elements containing
# scalar tensors.
dataset = tf.data.Dataset.from_tensor_slices(([1, 2], [3, 4], [5, 6]))
list(dataset.as_numpy_iterator())

[(1, 3, 5), (2, 4, 6)]

In [ ]:
dataset=tf.data.Dataset.from_tensors([1,2,3,4])
list(dataset.as_numpy_iterator())


[array([1, 2, 3, 4], dtype=int32)]

In [ ]:
dataset=tf.data.Dataset.from_tensors([1,2,3,4]).repeat(2)
list(dataset.as_numpy_iterator())

[array([1, 2, 3, 4], dtype=int32), array([1, 2, 3, 4], dtype=int32)]

In [ ]:
### Note that irrespective of the context in which map_func is defined 
### (eager vs. graph), tf.data traces the function and executes it as a graph.
dataset=tf.data.Dataset.range(1,8)
dataset=dataset.map(lambda x: x+1)
list(dataset.as_numpy_iterator())

[2, 3, 4, 5, 6, 7, 8]

In [ ]:
dataset=tf.data.Dataset.range(1,8)
dataset=dataset.map(lambda x: (x-1,x))
list(dataset.as_numpy_iterator())


[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7)]

In [ ]:
### tf.py_function and tf.numpy_function
d = tf.data.Dataset.from_tensor_slices(['hällö', 'wörld'])
# transform a string tensor to upper case string using a Python function
def up_trans(t:tf.Tensor):
  return t.numpy().decode('utf-8').upper()
d=d.map(lambda x: tf.py_function(func=up_trans, inp=[x], Tout=tf.string))
list(d.as_numpy_iterator())


[b'H\xc3\x84LL\xc3\x96', b'W\xc3\x96RLD']

In [ ]:
d = tf.data.Dataset.from_tensor_slices(['hällö', 'wörld'])
list(d)

[<tf.Tensor: shape=(), dtype=string, numpy=b'h\xc3\xa4ll\xc3\xb6'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'w\xc3\xb6rld'>]

In [ ]:
import numpy as np
d = tf.data.Dataset.from_tensor_slices(['hällö', 'wörld'])
def upper_case_fn(t: np.ndarray):
  return t.decode('utf-8').upper()
d = d.map(lambda x: tf.numpy_function(func=upper_case_fn,
          inp=[x], Tout=tf.string))
list(d.as_numpy_iterator())

[b'H\xc3\x84LL\xc3\x96', b'W\xc3\x96RLD']

In [ ]:
d = tf.data.Dataset.from_tensor_slices(['hällö', 'wörld'])
d.options()

In [ ]:
dataset = tf.data.Dataset.range(3)
dataset = dataset.prefetch(2)
list(dataset.as_numpy_iterator())

[0, 1, 2]

In [ ]:
print(list(tf.data.Dataset.range(1, 5, -2).as_numpy_iterator()))
print(list(tf.data.Dataset.range(5, 1).as_numpy_iterator()))
list(tf.data.Dataset.range(5, 1, -2).as_numpy_iterator())

[]
[]


[5, 3]

In [ ]:
tf.data.Dataset.range(5).reduce(np.int64(0), lambda x, y: x+y).numpy()

10

In [ ]:
### Repeats this dataset so each original value is seen count times.
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
dataset = dataset.repeat(3)
list(dataset.as_numpy_iterator())

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
dataset = tf.data.Dataset.range(3)
dataset = dataset.shuffle(3, reshuffle_each_iteration=True)
list(dataset.as_numpy_iterator())  # doctest: +SKIP

[1, 0, 2]

In [ ]:
list(dataset.as_numpy_iterator())  # doctest: +SKIP

[0, 1, 2]

In [ ]:
dataset = tf.data.Dataset.range(3)
dataset = dataset.shuffle(3, reshuffle_each_iteration=False)
list(dataset.as_numpy_iterator())  # doctest: +SKIP

[2, 1, 0]

In [ ]:
list(dataset.as_numpy_iterator())  # doctest: +SKIP

[2, 1, 0]

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.skip(7)
list(dataset.as_numpy_iterator())

[7, 8, 9]

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.take(3)
list(dataset.as_numpy_iterator())

[0, 1, 2]

In [ ]:
# The nested structure of the `datasets` argument determines the
# structure of elements in the resulting dataset.
a = tf.data.Dataset.range(1, 4)  # ==> [ 1, 2, 3 ]
b = tf.data.Dataset.range(4, 7)  # ==> [ 4, 5, 6 ]
ds = tf.data.Dataset.zip((a, b))
list(ds.as_numpy_iterator())

[(1, 4), (2, 5), (3, 6)]

In [ ]:
ds = tf.data.Dataset.zip((b, a))
list(ds.as_numpy_iterator())

[(4, 1), (5, 2), (6, 3)]