<a href="https://colab.research.google.com/github/Dmitri9149/TensorFlow-PyTorch-basics/blob/master/TensorFlow_SomeBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The work is for Tensorflow lerning, it is based ob the https://www.tensorflow.org/tutorials/quickstart/beginner



In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
x_train.shape

(60000, 28, 28)

In [4]:
### the code return float satatype, the tupling is ignored ?
x_train.dtype

dtype('float64')

In [5]:
### yes, the code returns the error
#(x_train, y_train).dtype
'''
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-654ba661b51d> in <module>()
----> 1 (x_train, y_train).dtype

AttributeError: 'tuple' object has no attribute 'dtype'
'''



"\n---------------------------------------------------------------------------\nAttributeError                            Traceback (most recent call last)\n<ipython-input-6-654ba661b51d> in <module>()\n----> 1 (x_train, y_train).dtype\n\nAttributeError: 'tuple' object has no attribute 'dtype'\n"

In [6]:
### Stacking layers, the model will return vector of 'logits'
model = tf.keras.models.Sequential([
### will transform 2D Tensor to 1D tensor  of size 28*28                              
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [7]:
### get logits , be carefulll have to supply slices 
### predictions = model(x_train[0]).numpy() will not work 
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.46375996,  0.34251824,  0.37452003, -0.44380432,  0.23354006,
        -0.14779092,  0.5893418 ,  0.55467516,  0.09166841,  0.45557582]],
      dtype=float32)

In [8]:
x_train[:1].shape

(1, 28, 28)

In [9]:
x_train[0].shape 

(28, 28)

In [10]:
a = [1, 2, 3]
print(a[0], " is not ", a[:1])

1  is not  [1]


In [11]:
### with .numpy()
predictions = model(x_train[:1]).numpy()
print("dtype = ",predictions.dtype)
print("shape = ",predictions.shape)

dtype =  float32
shape =  (1, 10)


In [12]:
### without .numpy()
predictions_a = model(x_train[:1])
print("dtype = ",predictions_a.dtype)
print("shape = ",predictions_a.shape)

dtype =  <dtype: 'float32'>
shape =  (1, 10)


In [13]:
### convert the output from linear layers to 'probabilities'
### take logits as input, return probabilities
tf.nn.softmax(predictions).numpy()

array([[0.11832996, 0.10481902, 0.10822768, 0.04774683, 0.09399646,
        0.06419505, 0.13416345, 0.12959215, 0.08156379, 0.11736548]],
      dtype=float32)

In [14]:
### construct loss function , 
### The losses.SparseCategoricalCrossentropy loss takes a vector of logits 
### and a True index and returns a scalar loss for each example.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [15]:
y_train[:1].shape

(1,)

In [16]:
y_train[:1].dtype

dtype('uint8')

In [17]:
### estimate the loss for the first example, untrained model
### without .numpy returns just a Tensor wrapper
loss_fn(y_train[:1], predictions)

<tf.Tensor: shape=(), dtype=float32, numpy=2.745829>

In [18]:
### with .numpy returns just digit
loss_fn(y_train[:1], predictions).numpy()

2.745829

In [19]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [20]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2935 - accuracy: 0.9150
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1434 - accuracy: 0.9560
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1071 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0874 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0758 - accuracy: 0.9761


In [21]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0781 - accuracy: 0.9766


[0.07806429266929626, 0.9765999913215637]

In [22]:
### we can add Softmax Layer and return probabilities from our model
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [23]:
probability_model(x_test[:1])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[2.1809930e-07, 1.1843574e-08, 2.3107884e-06, 7.6896773e-05,
        6.9249472e-12, 2.6909129e-07, 5.4253412e-13, 9.9991381e-01,
        4.0772591e-07, 6.1934452e-06]], dtype=float32)>