<a href="https://colab.research.google.com/github/Dmitri9149/TensorFlow-PyTorch-basics/blob/master/TensorFlow_SomeBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The work is for Tensorflow lerning, it is based ob the https://www.tensorflow.org/tutorials/quickstart/beginner



In [ ]:
import tensorflow as tf

In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
### the code return float satatype, the tupling is ignored ?
x_train.dtype

dtype('float64')

In [ ]:
### yes, the code returns the error
#(x_train, y_train).dtype
'''
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-654ba661b51d> in <module>()
----> 1 (x_train, y_train).dtype

AttributeError: 'tuple' object has no attribute 'dtype'
'''



"\n---------------------------------------------------------------------------\nAttributeError                            Traceback (most recent call last)\n<ipython-input-6-654ba661b51d> in <module>()\n----> 1 (x_train, y_train).dtype\n\nAttributeError: 'tuple' object has no attribute 'dtype'\n"

In [ ]:
### Stacking layers, the model will return vector of 'logits'
model = tf.keras.models.Sequential([
### will transform 2D Tensor to 1D tensor  of size 28*28                              
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [ ]:
### get logits , be carefulll have to supply slices 
### predictions = model(x_train[0]).numpy() will not work 
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.05917209, -0.05224019,  0.8960229 , -0.21260944, -0.27456933,
         0.11622985,  0.37518907, -0.35047618, -0.24944095, -0.04272584]],
      dtype=float32)

In [ ]:
x_train[:1].shape

(1, 28, 28)

In [ ]:
x_train[0].shape 

(28, 28)

In [ ]:
a = [1, 2, 3]
print(a[0], " is not ", a[:1])

1  is not  [1]


In [ ]:
### with .numpy()
predictions = model(x_train[:1]).numpy()
print("dtype = ",predictions.dtype)
print("shape = ",predictions.shape)

dtype =  float32
shape =  (1, 10)


In [ ]:
### without .numpy()
predictions_a = model(x_train[:1])
print("dtype = ",predictions_a.dtype)
print("shape = ",predictions_a.shape)

dtype =  <dtype: 'float32'>
shape =  (1, 10)


In [ ]:
### convert the output from linear layers to 'probabilities'
### take logits as input, return probabilities
tf.nn.softmax(predictions).numpy()

array([[0.09602685, 0.08590272, 0.22173405, 0.07317445, 0.06877817,
        0.10166525, 0.13171557, 0.06375066, 0.07052836, 0.08672394]],
      dtype=float32)

In [ ]:
### construct loss function , 
### The losses.SparseCategoricalCrossentropy loss takes a vector of logits 
### and a True index and returns a scalar loss for each example.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
y_train[:1].shape

(1,)

In [ ]:
y_train[:1].dtype

dtype('uint8')

In [ ]:
### estimate the loss for the first example, untrained model
### without .numpy returns just a Tensor wrapper
loss_fn(y_train[:1], predictions)

<tf.Tensor: shape=(), dtype=float32, numpy=2.2860696>

In [ ]:
### with .numpy returns just digit
loss_fn(y_train[:1], predictions).numpy()

2.2860696

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2983 - accuracy: 0.9136
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1445 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1081 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0894 - accuracy: 0.9733
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0765 - accuracy: 0.9757


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0817 - accuracy: 0.9749


[0.08173007518053055, 0.9749000072479248]

In [ ]:
### we can add Softmax Layer and return probabilities from our model
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:1])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[1.7685524e-08, 2.7176832e-09, 2.3706327e-06, 6.5009066e-05,
        7.2346074e-11, 3.1488913e-08, 2.9584972e-13, 9.9993110e-01,
        4.9917173e-08, 1.5218624e-06]], dtype=float32)>